<?php
$einame = $scname;
$eiadd = $scaddress;
$eicontact = $scmobile;
?>



<div class="full-box">
  <div>
    <h1 class="title-main">Tabulation Sheet</h1>
    <div class="title-exam">
      <?= htmlspecialchars($exam) ?> Examination - <?= htmlspecialchars($sessionyear) ?>
    </div>
    <div class="title-class">
      CLASS: <b><?= htmlspecialchars($cn) ?></b> | <b><?= htmlspecialchars($secname) ?></b>
    </div>
  </div>

  <div class="school-box">
    <div class="school-name"><?= htmlspecialchars($einame) ?></div>
    <div class="school-info"><?= htmlspecialchars($eiadd) ?></div>
    <div class="school-info"><?= htmlspecialchars($eicontact) ?></div>
  </div>

  <div class="report-generator">
    Report Generated by: <b>www.EIMBox.com</b> – Making your institution paperless
  </div>
</div>